name: Build Binaries

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      with: yarn install
    - name: Upgrade Packages to Specified Closure Version
      with: node ./build-scripts/bump-version.js
    - name: Compile Native Binary
      with: yarn build
    - name: Test Changes
      with: yarn test
    - name: Push Changes
      uses: kristoferbaxter/github-push-action@master
      with:
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}